name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Ensure full commit history is available

    - uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Get changed files
      id: changed_files
      run: |
        # Determine base branch for PRs
        if [[ "${{ github.event_name }}" == "pull_request" ]]; then
          BASE_BRANCH="origin/${{ github.base_ref }}"
        else
          BASE_BRANCH="HEAD^"
        fi

        # Get changed files
        CHANGED_FILES=$(git diff --name-only $BASE_BRANCH HEAD || true)
        echo "Changed files:"
        echo "$CHANGED_FILES"

        # Extract folder names and remove duplicates
        FOLDERS=$(echo "$CHANGED_FILES" | awk -F'/' '{print $1}' | sort -u | tr '\n' ' ' | sed 's/ *$//')
        echo "Changed folders: $FOLDERS"

        # Ensure the variable is not empty
        if [[ -z "$FOLDERS" ]]; then
          echo "No folder changes detected."
          FOLDERS="None"
        fi

        # Store it in an output variable for later steps
        echo "folders=$FOLDERS" >> $GITHUB_ENV

    - name: Print changed folders
      run: echo "Modified folders: '${{ env.folders }}'"
