name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Ensure full commit history is available

    - uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Get changed files
      id: changed_files
      run: |
        # Get the changed files in a PR
        if [ "$GITHUB_EVENT_NAME" == "pull_request" ]; then
          CHANGED_FILES=$(git diff --name-only origin/${{ github.base_ref }} HEAD)
        else
          CHANGED_FILES=$(git diff --name-only HEAD^ HEAD)
        fi

        echo "Changed files:"
        echo "$CHANGED_FILES"

        # Extract folder names and remove duplicates
        FOLDERS=$(echo "$CHANGED_FILES" | awk -F'/' '{print $1}' | sort -u)
        echo "Changed folders:"
        echo "$FOLDERS"

        # Store it in an output variable for later steps
        echo "folders=$FOLDERS" >> $GITHUB_ENV

    - name: Print changed folders
      run: echo "Modified folders: ${{ env.folders }}"

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run Playwright tests
      run: npx playwright test

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
